[project]
name = "ncm_catcher"
version = "1.1.0"
description = "从Windows窗口标题获取PC端网易云音乐当前播放歌名并支持写入文件，可通过OBS读取"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pywin32>=310",
    "pyinstaller>=6.14.1",
]
